### PR TITLE
Add support for custom gossipsub protocols

### LINKED ISSUE #408: Question: Extending Gossipsub protocol list
Is it possible to extend the list of protocols returned in:
https://github.com/libp2p/go-libp2p-pubsub/blob/5457a2845b06d859df6d3683867808e46a15c500/gossipsub.go#L401-L403
I'd like to include an additional ID besides `GossipSubID_v11, GossipSubID_v10, FloodSubID`, yet I find it difficult to extend GossipSubRouter to include my custom ID. 

Floodsub supports this feature with `NewFoodsubWithProtocols` 
https://github.com/libp2p/go-libp2p-pubsub/blob/5457a2845b06d859df6d3683867808e46a15c500/floodsub.go#L17-L22
Is adding a similar functionality something viable? I could create a PR that adds a `NewGossipsubWithProtocols(ctx context.Context, h host.Host, ps []protocol.ID, opts ...Option) (*PubSub, error)`

### PR DESCRIPTION
**Pull request by vyzo**
This adds support for custom gossipsub protocols, with an associated feature test function, and a gossipsub router option to specify them.

Closes #408

### CODE REVIEW

**Review by Stebalien — APPROVED** [review]

**Comment by Stebalien** [comment]
Except CI needs some fixing.

**Comment by vyzo** [comment]
travis has gone AWOL since yesterday; what's worse it doesn't even let me restart the builds (and it didn't let @raulk either).

We need to move away from it ASAP.

**Comment by vyzo** [comment]
fwis tests all pass locally.

**Comment by Stebalien** [comment]
Merge when comfortable.

**Pull request merged**
