### PR TITLE
add test for tracers

### PR DESCRIPTION
**Pull request by vyzo**
See #287

### CODE REVIEW

**Review by dirkmc — APPROVED** [review]
LGTM 👍 

It may make sense to reduce the heartbeat so that the test runs faster

**Comment by dirkmc** [comment]
Also it looks from the CI logs like there's a race in the test:
```
WARNING: DATA RACE
Write at 0x00c00032e730 by goroutine 231:
  runtime.closechan()
      /home/travis/.gimme/versions/go1.14.2.linux.amd64/src/runtime/chan.go:335 +0x0
  github.com/libp2p/go-libp2p-pubsub.(*basicTracer).Close()
      /home/travis/gopath/src/github.com/libp2p/go-libp2p-pubsub/tracer.go:72 +0x125
  github.com/libp2p/go-libp2p-pubsub.TestRemoteTracer()
      /home/travis/gopath/src/github.com/libp2p/go-libp2p-pubsub/trace_test.go:318 +0x455
  testing.tRunner()
      /home/travis/.gimme/versions/go1.14.2.linux.amd64/src/testing/testing.go:991 +0x1eb
Previous read at 0x00c00032e730 by goroutine 2779:
  ??()
      -:0 +0xffffffffffffffff
  github.com/libp2p/go-libp2p-pubsub.(*pubsubTracer).RecvRPC()
      /home/travis/gopath/src/github.com/libp2p/go-libp2p-pubsub/trace.go:227 +0x4ca
  github.com/libp2p/go-libp2p-pubsub.(*PubSub).handleIncomingRPC()
      /home/travis/gopath/src/github.com/libp2p/go-libp2p-pubsub/pubsub.go:756 +0x93
  github.com/libp2p/go-libp2p-pubsub.(*PubSub).processLoop()
      /home/travis/gopath/src/github.com/libp2p/go-libp2p-pubsub/pubsub.go:513 +0x10ee
```

**Comment by vyzo** [comment]
I can't reproduce the races locally though, so I am not sure what's up with that.

**Comment by vyzo** [comment]
I think we might be able to get around this by adding some delay before closing the tracer, just to make sure the host (and pubsub) is closed.

**Comment by vyzo** [comment]
ok, I think the race might be legitimate; we need to hold the lock before writing the notification channel in the tracer implementation.

**Comment by vyzo** [comment]
let's see if this fixes it.

**Comment by vyzo** [comment]
looks like it did!

**Comment by vyzo** [comment]
We keep getting this kind of errors in travis:
```
$ go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

**Pull request merged**
