### PR TITLE
Re-enable disabled gossipsub test

### PR DESCRIPTION
**Pull request by Stebalien**

### CODE REVIEW

**Review by vyzo — APPROVED** [review]

**Comment by vyzo** [comment]
wait, it fails!!!

**Comment by Stebalien** [comment]
It does. I have no idea what this test is supposed to be doing, TBH. But it was supposed to be re-enabled.

**Comment by Stebalien** [comment]
Still broken...

**Comment by Stebalien** [comment]
@vyzo I finally looked into this and fixed the issue.

**Review by vyzo — APPROVED** [review]
thank you!

**Pull request merged**
