### PR TITLE
ci: add windows ci

### PR DESCRIPTION
**Pull request by aschmahmann**
I've noticed some issues when running tests on Windows, we should really track this in CI.

@vyzo how do you feel about moving away from Travis? @marten-seemann has been working on some CI standardization using GitHub actions in https://github.com/ipld/.github/

### CODE REVIEW

**Comment by vyzo** [comment]
Sure, we are not married to travis.

**Comment by marten-seemann** [comment]
We can include this repo in the new GitHub Actions workflow, as soon as we get it deployed PL-wide.

**Comment by vyzo** [comment]
Sure let's do that.

@aschmahmann the windows ci is timing out; this is probably travis sucking, but maybe there is a real issue underneath.

**Comment by aschmahmann** [comment]
@vyzo I think this is a real thing, not just Travis. This sometimes happens on my laptop too.

There are also a couple test failures related to writing to /tmp instead of Go's OS agnostic temporary directory.

**Comment by vyzo** [comment]
care to fix those tests in the pr?

**Comment by aschmahmann** [comment]
Yep, I can definitely do the `/tmp` fixes here. The hanging might take me some time before I can look into it though

**Comment by vyzo** [comment]
we have dropped travis, as it is horribly broken; closing.

**Pull request closed without merging**
