### PR TITLE
Add example chat app

### PR DESCRIPTION
**Pull request by yusefnapora**
This adds a chat room example, to show the basic `PubSub` API.

I started writing a more complicated example to specifically highlight the features added in gossipsub v1.1, but since we don't have this introductory example yet, I kept getting drawn off track explaining the basics.

I'm still planning to finish the gossipsub v1.1 example, but I wanted to get this in first so I can assume people know the basics and refer them here if not.

### CODE REVIEW

**Comment by yusefnapora** [comment]
It's just now occurring to me that this really belongs in the go-libp2p-examples repo... I'll move it in the morning :)

**Review by vyzo — APPROVED** [review]
LGTM; great work!

**Comment by vyzo** [comment]
Actually yeah, let's move to `go-libp2p-examples`.

**Comment by vyzo** [comment]
Closing to move to `go-libp2p-examples`; I feel sad about it because this is _nice code_, but it belongs there as you say.

**Pull request closed without merging**
