### PR TITLE
update Gx/libp2p-dep branch

### PR DESCRIPTION
**Pull request by lanzafame**
cc @hsanjuan

### CODE REVIEW

**Comment by vyzo** [comment]
Can you rebase this?

**Comment by vyzo** [comment]
Also, publish 100.9.28? really?

**Comment by lanzafame** [comment]
@vyzo see https://github.com/ipfs/ipfs-cluster/pull/544#discussion_r219668254 for the explanation.

**Review by hsanjuan — APPROVED** [review]

**Comment by hsanjuan** [comment]
This is **not** going into master. It's going into a branch we can work with in terms of dependencies.

**Comment by hsanjuan** [comment]
@lanzafame can you resolve the conflicts ?

**Comment by lanzafame** [comment]
@hsanjuan resolved and test are passing

**Comment by vyzo** [comment]
You are going to have to maintain this branch though.

**Comment by hsanjuan** [comment]
I've been doing it for a while. Sorry for the noise.

**Pull request merged**
