### PR TITLE
tests to increase coverage in pubsub.go and validation.go

### PR DESCRIPTION
**Pull request by vyzo**
See #287.
Also fixes a bug discovered in WithMessageAuthor option.

### CODE REVIEW

**Comment by vyzo** [comment]
`TestPeerDisconnect`, which is one of our ancient tests, failed:
```
=== RUN   TestPeerDisconnect

    TestPeerDisconnect: floodsub_test.go:710: mismatch: [] != [12D3KooWAF7Yj1GZKwr3SewZF4tH813rkEUNkehnzDnxF4Q6RGGE]
```

**Comment by vyzo** [comment]
hrm, data race in `TestFanOutExpiry`:
```
==================

WARNING: DATA RACE

Read at 0x0000013c05a0 by goroutine 2042:

  github.com/libp2p/go-libp2p-pubsub.(*GossipSubRouter).heartbeat()

      /home/travis/gopath/src/github.com/libp2p/go-libp2p-pubsub/gossipsub.go:1073 +0x1c30

  github.com/libp2p/go-libp2p-pubsub.(*GossipSubRouter).heartbeat-fm()

      /home/travis/gopath/src/github.com/libp2p/go-libp2p-pubsub/gossipsub.go:934 +0x41

  github.com/libp2p/go-libp2p-pubsub.(*PubSub).processLoop()

      /home/travis/gopath/src/github.com/libp2p/go-libp2p-pubsub/pubsub.go:530 +0xf0e

Previous write at 0x0000013c05a0 by goroutine 1850:

  [failed to restore the stack]

Goroutine 2042 (running) created at:

  github.com/libp2p/go-libp2p-pubsub.NewPubSub()

      /home/travis/gopath/src/github.com/libp2p/go-libp2p-pubsub/pubsub.go:255 +0x1296

  github.com/libp2p/go-libp2p-pubsub.NewGossipSub()

      /home/travis/gopath/src/github.com/libp2p/go-libp2p-pubsub/gossipsub.go:121 +0x64b

  github.com/libp2p/go-libp2p-pubsub.getGossipsub()

      /home/travis/gopath/src/github.com/libp2p/go-libp2p-pubsub/gossipsub_test.go:27 +0x15d

  github.com/libp2p/go-libp2p-pubsub.getGossipsubs()

      /home/travis/gopath/src/github.com/libp2p/go-libp2p-pubsub/gossipsub_test.go:37 +0xc5

  github.com/libp2p/go-libp2p-pubsub.TestGossipsubFanoutMaintenance()

      /home/travis/gopath/src/github.com/libp2p/go-libp2p-pubsub/gossipsub_test.go:198 +0x14f

  testing.tRunner()

      /home/travis/.gimme/versions/go1.14.2.linux.amd64/src/testing/testing.go:991 +0x1eb

Goroutine 1850 (running) created at:

  testing.(*T).Run()

      /home/travis/.gimme/versions/go1.14.2.linux.amd64/src/testing/testing.go:1042 +0x660

  testing.runTests.func1()

      /home/travis/.gimme/versions/go1.14.2.linux.amd64/src/testing/testing.go:1284 +0xa6

  testing.tRunner()

      /home/travis/.gimme/versions/go1.14.2.linux.amd64/src/testing/testing.go:991 +0x1eb

  testing.runTests()

      /home/travis/.gimme/versions/go1.14.2.linux.amd64/src/testing/testing.go:1282 +0x527

  testing.(*M).Run()

      /home/travis/.gimme/versions/go1.14.2.linux.amd64/src/testing/testing.go:1199 +0x2ff

  main.main()

      _testmain.go:278 +0x337

==================
```

**Comment by vyzo** [comment]
damn the race detector, it's the fanoutTTL restore that is triggering it.
I will reify this into the router struct as well.

**Review by dirkmc — APPROVED** [review]

**Comment by vyzo** [comment]
the build errored with the travis timeout in https://github.com/libp2p/go-libp2p-pubsub/pull/303/checks?check_run_id=612311806 -- see https://travis-ci.com/github/libp2p/go-libp2p-pubsub/jobs/322584899
I am going to take the opportunity to increase the wait to ~25~30min, this ought to be enough!

**Pull request merged**
