### PR TITLE
Basic example with README

### PR DESCRIPTION
**Pull request by nikkolasg**
This PR is a proposition to add a basic example on how to use the pubsub library. Since I had to go through the tests to find out, it may be helpful for others to have a clear and simple example first.
The code is from the issue https://github.com/libp2p/go-libp2p-pubsub/issues/142 
It's just a proposition, feel free to postpone if you had other plans (other repo, etc).

**NOTE** It does not work when the connections (line 55 - 57) happen *before* creating the `PubSub` and registering the topic.. I don't know why. Is this expected ? (@vyzo I tried increasing the timeout but it still hangs).

### CODE REVIEW

**Comment by vyzo** [comment]
Do you mind adding this to `go-libp2p-examples` instead?
That is the central place for libp2p example code, and we don't have anything for pubsub yet.

Note the reason it doesn't work if you connect before creating the pubsub is that there are no connection notifications, so the peers are not discovered.

**Comment by nikkolasg** [comment]
> Do you mind adding this to go-libp2p-examples instead?

Sure, will do :)    - although I'm not sure to understand why travis complains about missing dependencies ... not familiar with this setup -

> Note the reason it doesn't work if you connect before creating the pubsub is that there are no connection notifications, so the peers are not discovered.

But even, after the creation of the pubsub, there will be no "connections notifications" as well, no ? Why having the pubsub before changes anything ?  The pubsub will likely send some notifications, but I don't understand that it works only when the notifications are sent in a non-opened connection yet ... ?

In any case, it's a bit a surprising behavior and can raise weird questions - do I need to subscribe to all topics before connecting ?, etc - : if the opportunity arises, it'd a good thing to document or change so it always work regardless of the order ;)

**Comment by vyzo** [comment]
It's only the construction of the pubsub object that must precede the connections.
You can then connect before subscribing.

**Comment by JackBekket** [comment]
It's acctually would be nice to see pubsub in examples

**Pull request closed without merging**
