### PR TITLE
Improve handling of dead peers

### PR DESCRIPTION
**Pull request by Wondertan**
Related to #506

### CODE REVIEW

**Review by vyzo — APPROVED** [review]
yup, nice and simple.

**Review by vyzo — CHANGES_REQUESTED** [review]
Wait, should it have length at least 1?
Its busy loop otherwise.

**Comment by Wondertan** [comment]
Ohh, right, fixed

**Review by vyzo — APPROVED** [review]
ok, looks great now; a redish diff!

**Comment by vyzo** [comment]
I'd like to cut a patch release with these patches, can you do some sanity testing before I fo so?

**Comment by Wondertan** [comment]
All the tests pass locally, or what do you mean?

**Comment by vyzo** [comment]
Run a canary node in production for a day or two?

**Comment by Wondertan** [comment]
@vyzo, Ok. I started my lotus daemon and miner on pubsub's master with the recent changes. I will report back on how it is going in a few days. It should give us enough confidence

**Comment by Wondertan** [comment]
@vyzo, 5 days of stable sync - :shipit:

**Comment by vyzo** [comment]
altight, i'll tag a release on momday. Thank you!

**Pull request merged**
